
# Do NOT edit this file. Instead, just call it from the command line,
# using the instructions in the assignment notebook.

import sys
questions = sys.argv[1:]


valid_ids = ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8']
break_flag = False
invalid_ids = []
for question in questions:
    if question != 'all' and question not in valid_ids:
        invalid_ids.append(question)

if len(invalid_ids) > 0:
    print(str(invalid_ids) + ' is/are not a valid question number(s). The possible question numbers are ' + str(valid_ids) + '.')
    sys.exit()

# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# %load_ext autoreload
# %autoreload 2

from lab import *

import pandas as pd
import numpy as np
import sys
import os
from dsc80_utils import *


parks = pd.read_csv('data/parks.csv')
visits = pd.read_csv('data/visits.csv', parse_dates=['entry'])

parks.head(2)

visits.head(2)

df1 = parks.merge(visits, on='park_id', how='inner')
df2 = parks.merge(visits, on='park_id', how='left')

if 'q1' in questions or questions == [] or 'all' in questions:
    print(grader.check("q1"))

if 'q2' in questions or questions == [] or 'all' in questions:
    print(grader.check("q2"))

if 'q3' in questions or questions == [] or 'all' in questions:
    print(grader.check("q3"))

df = pd.read_csv('data/visits_missing_a.csv')
df

if 'q4' in questions or questions == [] or 'all' in questions:
    print(grader.check("q4"))

if 'q5' in questions or questions == [] or 'all' in questions:
    print(grader.check("q5"))

if 'q6' in questions or questions == [] or 'all' in questions:
    print(grader.check("q6"))

## don't delete this cell, but do run it -- it is needed for the autograder tests
mar_cols = mar_cols_function()
pval = pvals_function()

if 'q7' in questions or questions == [] or 'all' in questions:
    print(grader.check("q7"))

## don't delete this cell, but do run it -- it is needed for the autograder tests
np.random.seed(42)
df_imputed = df_imputed_function()

if 'q8' in questions or questions == [] or 'all' in questions:
    print(grader.check("q8"))


